tarot_cards = [
    'The World (upright): fulfillment, harmony, completion', 
    'The World (reversed): incompletion, no closure', 
    'Judgement (upright): reflection, reckoning, awakening',
    'Judgement (reversed): lack of self awareness, doubt, self loathing',
    'The Sun (upright): joy, success, celebration, positivity',
    'The Sun (reversed): negativity, depression, sadness',
    'The Moon (upright): unconscious, illusions, intuition',
    'The Moon (reversed): confusion, fear, misinterpretation',
    'The Star (upright): hope, faith, rejuvenation',
    'The Star (reversed): faithlessness, discouragement, insecurity',
    'The Tower (upright): sudden upheaval, broken pride, disaster',
    'The Tower (reversed): disaster avoided, delayed disaster, fear of suffering',
    'The Devil (upright): addiction, materialism, playfulness',
    'The Devil (reversed): freedom, release, restoring control',
    'Temperance (upright): middle path, patience, finding meaning',
    'Temperance (reversed): extremes, excess, lack of balance',
    'Death (upright): end of cycle, beginnings, change, metamorphosis',
    'Death (reversed): resistance to change, personal transformation, inner purging',
    'The Hanged Man (upright): sacrifice, release, martyrdom',
    'The Hanged Man (reversed): stalling, needless sacrifice, fear of sacrifice',
    'Justice (upright): cause and effect, clarity, truth',
    'Justice (reversed): dishonesty, unaccountability, unfairness',
    'The Wheel of Fortune (upright): change, cycles, inevitable fate',
    'The Wheel of Fortune (reversed): no control, clinging to control, bad luck',
    'The Hermit (upright): contemplation, search for truth, inner guidance',
    'The Hermit (reversed): loneliness, isolation, lost your way',
    'Strength (upright): inner strength, bravery, compassion, focus',
    'Stength (reversed): self doubt, weakness, insecurity',
    'The Chariot (upright): direction, control, willpower',
    'The Chariot (reversed): lack of control, lack of direction, aggression',
    'The Lovers (upright): partnerships, duality, union',
    'The Lovers (reversed): loss of balance, one-sidedness, disharmony',
    'The Hierophant (upright): tradition, conformity, morality, ethics',
    'The Hierophant (revsersed): rebellion, subversiveness, new approaches',
    'The Emperor (upright): authority, structure, control, fatherhood',
    'The Emperor (reversed): tyranny, rigidity, coldness',
    'The Empress (upright): motherhood, fertility, nature',
    'The Empress (reversed): dependence, smothering, emptiness, nosiness',
    'The High Priestess (upright): intuitive, unconscious, inner voice',
    'The High Priestess (reversed): lack of center, lost inner voice, repressed feelings',
    'The Magician (upright): willpower, desire, creation, manifestation',
    'The Magician (reversed): trickery, illusions, out of touch',
    'The Fool (upright): innocence, new beginnings, free spirit',
    'The Fool (reversed): recklessness, taken advantage of, inconsideration'
]
